fix: sort leaves by their hashes
rkdud007/alloy-merkle-tree pull request #10
Opened 2024-12-20 11:27 UTC by 0xfffxfff

This PR fixes the implementation of the standard tree by sorting the leaves by their hashes. Test included.

For reference this is implemented in the openzeppelin implementation here: https://github.com/OpenZeppelin/merkle-tree/blob/master/src/merkletree.ts#L69-L71

2024-12-21 04:22 UTC, rkdud007 requested changes

2024-12-21 04:22 UTC, rkdud007 commented on src/standard_binary_tree.rs
> +        // Sort the hashed values by their hash.
imo this should be optional e.g oz merkle tree implementation passing sort flag as option (https://github.com/OpenZeppelin/merkle-tree/blob/master/src/options.ts#L2).

e.g
```rust
pub fn of(values: &[DynSolValue], sortLeaves: Option<bool>) -> Self
```

2024-12-22 00:07 UTC, 0xfffxfff commented
Alright! Added a separate method `of_sorted` and restored the original method `of`.

2024-12-22 13:49 UTC, rkdud007 requested changes
thanks fix ci then lgtm

2024-12-22 15:17 UTC, merged

2024-12-22 15:18 UTC, rkdud007 commented
thanks for contribution!